name: Everton Muniz - Blog
description: Falando sobre desenvolvimento para web
meta_description: "Desenvolvimento Web, Testes, PHP"

markdown: redcarpet
highlighter: pygments
paginate: 15
baseurl: /
domain_name: 'http://munizeverton.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
img_path: /assets/images/

# Details for the RSS feed generator
url: 'http://munizeverton.github.io/'
author:
    name: Everton Muniz
    thumb: /assets/images/profile.jpg
    bio: Desenvolvedor web
    url:
        linkedin: 'https://br.linkedin.com/in/munizeverton'
        github: 'https://github.com/munizeverton'